apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ci-cd-kube-ingress
  labels:
    app: ci-cd-kube
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - 138.201.184.143.sslip.io
        - etudiant-05.development.atelier.ovh
      secretName: ci-cd-kube-tls
  rules:
    - host: etudiant-05.development.atelier.ovh
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ci-cd-kube-service
                port:
                  number: 80
    - host: 138.201.184.143.sslip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ci-cd-kube-service
                port:
                  number: 80
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ci-cd-kube-service
                port:
                  number: 80


